require "config.options"
require "config.keymaps"
require "config.lsp"
-- require "config.mason"
require "config.diagnostic"
require "config.lualine"
require "config.undo"
require "config.mini_snippets"
-- require "config.mini_icons"
require "config.dap"
require "config.mini_surround"
require "config.telescope"
require "config.colorschemes"
require "config.todo_comments"
require "config.colorizer"
require "config.neogit"
-- require "config.lazydev"
-- require "config.conform"
--require "config.luasnip"
